// SPDX-License-Identifier: AGPL-3.0-or-later
// Based on Abyssal Claims — © 2026 Michal Mazurowski — https://something-rare.com

// The safety net for the eventual Map3DControls.tsx split (3,369 lines, ~57
// <LayerRow> instances across 2 <GroupHeader> sections and 10 <SubGroup>s,
// 34 inline filterContent blocks, one flat ~140-field useMapStore()
// destructure plus 10 parent props).
//
// A later refactor that moves this code across per-section files must not
// change what gets rendered, which localStorage keys panel state is
// persisted under, or which filter chips a given layer shows — this test is
// the invariant that proves it didn't.
//
// Conventions follow src/__tests__/detail-panel-matrix.test.tsx: real
// Zustand store (not a module mock), frozen system time, i18n initialised in
// src/test/setup.ts, per-URL fetch router that rejects on an unmatched URL.
import { describe, it, expect, vi, beforeEach, afterEach } from "vitest";
import { act, render, cleanup } from "@testing-library/react";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { Map3DControls } from "../components/Map3DControls";
import { useMapStore } from "../store/mapStore";

// Map3DControls.tsx is being split section-by-section into
// src/components/controls/sections/*Section.tsx (see that directory's
// growing file list). SOURCE below concatenates the main file with every
// section file already extracted, so this structural safety net keeps
// working as sub-groups move out — it is checking "what does the panel
// render", not "which file is it written in".
const SECTION_FILES = [
  "ClaimsZonesSection.tsx",
  "LifeGeologySection.tsx",
  "AnalysisSection.tsx",
  "SensorsSection.tsx",
  "OceanClimatologySection.tsx",
  "oceanClimatology/WoaClimatologyRow.tsx",
  "oceanClimatology/OceanCarbonRow.tsx",
  "oceanClimatology/OceanCo2SurfaceRow.tsx",
  "oceanClimatology/WodOxygenRow.tsx",
  "oceanClimatology/MementoRow.tsx",
  "oceanClimatology/GeotracesRow.tsx",
  "oceanClimatology/MosaicSedimentRow.tsx",
  "oceanClimatology/MethaneSeepsRow.tsx",
  "oceanClimatology/OxygenDeoxRow.tsx",
  "oceanClimatology/ArcticRiversRow.tsx",
  "oceanClimatology/ArcticCatchmentsRow.tsx",
  "oceanClimatology/ArcticSedimentCarbonRow.tsx",
  "oceanClimatology/PermafrostThawRow.tsx",
  "oceanClimatology/SiosSvalbardRow.tsx",
  "oceanClimatology/SeabedSubstrateRow.tsx",
  "MarhysRow.tsx",
  "InfrastructureSection.tsx",
  "UnderwaterNoiseSection.tsx",
  "LandCoreSection.tsx",
  "HazardsMonitoringSection.tsx",
  "WaterCarbonSection.tsx",
];
const SOURCE = [
  readFileSync(resolve(__dirname, "../components/Map3DControls.tsx"), "utf-8"),
  ...SECTION_FILES.map((f) =>
    readFileSync(resolve(__dirname, `../components/controls/sections/${f}`), "utf-8"),
  ),
].join("\n");

// ── 1. Every layer row ───────────────────────────────────────────────────
//
// 53 of the 58 rows are literal `<LayerRow id="...">` blocks. The remaining
// 5 (reserved-areas, relinquished-areas, apeis, protected-marine-sites, eez)
// are generated by a single `.map(cfg => <LayerRow id={cfg.id} .../>)` over
// an inline array — the one dynamic block in the file (grep for
// `id={cfg.id}` to find it again). Both halves are re-derived from source
// here so the count doesn't drift silently if a literal id is renamed.
function deriveLayerRowIds(): string[] {
  const ids: string[] = [];
  const lines = SOURCE.split("\n");
  for (let i = 0; i < lines.length; i++) {
    if (!lines[i].includes("<LayerRow")) continue;
    const chunk = lines.slice(i, i + 8).join("\n");
    const m = chunk.match(/id="([^"]*)"/);
    if (m) ids.push(m[1]);
  }
  return ids;
}

// The 5 ids behind the .map(cfg => ...) block — read straight out of the
// inline config array literal so this list can't drift from the source
// independently of the array it's describing.
function deriveMappedLayerRowIds(): string[] {
  const m = SOURCE.match(/\(\[\s*\{ id: "reserved-areas",[\s\S]*?\] as \{ id: LayerId/);
  if (!m) return [];
  return [...m[0].matchAll(/id: "([^"]*)"/g)].map((x) => x[1]);
}

const LITERAL_IDS = deriveLayerRowIds();
const MAPPED_IDS = deriveMappedLayerRowIds();
const ALL_LAYER_IDS = [...LITERAL_IDS, ...MAPPED_IDS];

// Hard-coded count: 53 literal + 5 array-driven = 58. If this changes, a
// layer was added or lost from the left-hand menu — go find which.
//   59 → 58 on 2026-09-03: `wdpa` withdrawn pending UNEP-WCMC permission.
//   58 → 57 on 2026-09-03: `kbas` withdrawn under the same BirdLife clause.
//   57 → 58 on 2026-09-23: `marhys` added (MARHYS vent fluid chemistry).
const EXPECTED_LAYER_ROW_COUNT = 58;

const SUBGROUP_STORAGE_KEYS = [
  "sea_claims", "sea_life", "sea_analysis", "sea_sensors", "sea_woa",
  "sea_infra", "sea_vessels", "land_core", "land_hazards", "land_water",
];

function jsonResponse(data: unknown) {
  return { ok: true, status: 200, json: async () => data, text: async () => JSON.stringify(data) };
}

// Map3DControls fires 3 of its own fetches (independent of the meta props),
// each gated on activation state so most test states never trigger them —
// but a couple of the representative-filter and prop-driven snapshots do.
const ROUTES: Array<[RegExp, unknown]> = [
  [/\/v2\/spatial\/offshore-activities\/countries/, [{ sovereign: "Norway", count: 12 }]],
  [/\/v1\/acidification\/meta/, { variables: [], depths: [] }],
  [/\/v1\/chi\/meta/, { variables: [], depths: [] }],
];
const fetchMock = vi.fn(async (url: string) => {
  const hit = ROUTES.find(([re]) => re.test(url));
  if (hit) return jsonResponse(hit[1]);
  return Promise.reject(new Error(`Unmocked fetch in map3d-controls.test.tsx: ${url}`));
});

// jsdom does not implement window.matchMedia — Map3DControls calls it
// synchronously (isMobile()) on every render to decide mobile vs desktop
// layout. Without this stub every render throws "matchMedia is not a
// function" before any assertion runs.
function stubMatchMedia(matchesMobile: boolean) {
  vi.stubGlobal("matchMedia", (query: string) => ({
    matches: query.includes("max-width") ? matchesMobile : false,
    media: query,
    onchange: null,
    addListener: () => {},
    removeListener: () => {},
    addEventListener: () => {},
    removeEventListener: () => {},
    dispatchEvent: () => false,
  }));
}

// Panel open/section-expand/subgroup-expand state is all localStorage-backed
// (`abyssal_layers_panel`, `abyssal_subgroups`) so it persists across
// reloads for real users — which means it also leaks across tests unless
// reset. Seed it fully expanded so every row in the component is actually
// mounted and visible to the assertions below, rather than hidden behind a
// collapsed section/subgroup.
function seedExpandedPanelState() {
  localStorage.setItem(
    "abyssal_layers_panel",
    JSON.stringify({ open: true, seaOpen: true, landOpen: true, expandedFilter: null }),
  );
  const allExpanded = Object.fromEntries(SUBGROUP_STORAGE_KEYS.map((k) => [k, true]));
  localStorage.setItem("abyssal_subgroups", JSON.stringify(allExpanded));
}

beforeEach(() => {
  localStorage.clear();
  stubMatchMedia(false);
  vi.stubGlobal("fetch", fetchMock);
  vi.setSystemTime(new Date("2026-08-20T12:00:00Z"));
  // Reset the handful of store fields these tests actually touch — mirrors
  // detail-panel-matrix.test.tsx's beforeEach, not a full store rebuild.
  useMapStore.getState().resetAllFilters?.();
  useMapStore.setState({ activeLayers: new Set(), enabledLayerIds: null });
});

afterEach(() => {
  cleanup();
  vi.unstubAllGlobals();
  vi.useRealTimers();
});

const noop = () => {};
const baseProps = {
  claimsData: null,
  currentsMeta: null,
  currentsDate: null,
  setCurrentsDate: noop,
  currentsPlaying: false,
  setCurrentsPlaying: noop,
  woaMeta: null,
  oxygenMeta: null,
  carbonMeta: null,
  co2Meta: null,
};

// Shapes taken verbatim from the `Props` interface at the top of
// Map3DControls.tsx, not invented — a wrong shape here would make the
// "with metas" snapshot exercise fields the real component never reads.
const rampEntry = { pos: 0, hex: "#000000" };
const woaMetaFull = {
  variables: [{ key: "temp", label: "Temperature", units: "°C", vmin: 0, vmax: 30, cmap: "viridis", baseline: "1991-2020", depths: [0, 100], ramp: [rampEntry] }],
  depths: [0, 100],
};
const oxygenMetaFull = {
  views: [{ key: "recent", label: "Recent O2", units: "µmol/kg", vmin: 0, vmax: 300, cmap: "viridis", ramp: [rampEntry], depths: [0, 100], diverging: false }],
  depths: [0, 100],
  attribution: "ISAS20 BGC-Argo",
};
const carbonMetaFull = {
  variables: [{ key: "dic", label: "DIC", units: "µmol/kg", vmin: 1900, vmax: 2300, cmap: "viridis", baseline: "2016b", depths: [0, 100], ramp: [rampEntry] }],
  depths: [0, 100],
};
const co2MetaFull = {
  variables: [{ key: "fco2", label: "fCO2", units: "µatm", vmin: 280, vmax: 450, cmap: "viridis", ramp: [rampEntry] }],
  decades: [{ index: 5, label: "2020s" }],
};
const currentsMetaFull = {
  surface: {
    url: "https://example.test/currents/surface.png",
    bounds: [-180, -90, 180, 90] as [number, number, number, number],
    imageUnscale: [-3, 3] as [number, number],
    date: "2026-08-01",
    depth_label: "Surface",
    width: 720,
    height: 360,
  },
};

describe("Map3DControls source structure", () => {
  it("finds exactly 58 layer rows (53 literal + 5 array-driven)", () => {
    expect(LITERAL_IDS).toHaveLength(53);
    expect(MAPPED_IDS).toEqual(["reserved-areas", "relinquished-areas", "apeis", "protected-marine-sites", "eez"]);
    expect(ALL_LAYER_IDS).toHaveLength(EXPECTED_LAYER_ROW_COUNT);
    // No id appears twice — a duplicate id would mean two rows silently
    // fighting over the same activeLayers.has(id)/toggle(id) state.
    expect(new Set(ALL_LAYER_IDS).size).toBe(EXPECTED_LAYER_ROW_COUNT);
  });

  it("declares exactly the 10 known subgroup storageKeys", () => {
    // These strings are localStorage keys (abyssal_subgroups). Renaming one
    // silently resets every existing user's panel-open state — assert the
    // exact literal, not just "10 keys exist".
    const found = [...SOURCE.matchAll(/storageKey="([^"]*)"/g)].map((m) => m[1]);
    expect(found.sort()).toEqual([...SUBGROUP_STORAGE_KEYS].sort());
    expect(found).toHaveLength(10);
  });
});

describe("Map3DControls rendering", () => {
  it("renders a checkbox row for every one of the 58 layer ids", () => {
    seedExpandedPanelState();
    const { container } = render(<Map3DControls {...baseProps} />);
    // LayerRow's toggle <input> is the only checkbox in the tree carrying
    // the "peer" class (filter-chip checkboxes inside filterContent don't
    // use it) — a reliable, refactor-proof way to count rows without
    // depending on translated label text.
    const rowCheckboxes = container.querySelectorAll('input.peer[type="checkbox"]');
    expect(rowCheckboxes).toHaveLength(EXPECTED_LAYER_ROW_COUNT);
  });

  it("renders both group headers and all 10 subgroups expanded", () => {
    seedExpandedPanelState();
    const { getByText } = render(<Map3DControls {...baseProps} />);
    expect(getByText("Sea Data")).toBeInTheDocument();
    expect(getByText("Land Data")).toBeInTheDocument();
  });

  it("carries the layers-panel tutorial hook and exactly one locate-btn hook", () => {
    seedExpandedPanelState();
    const { container } = render(<Map3DControls {...baseProps} />);
    expect(container.querySelectorAll('[data-tutorial="layers-panel"]')).toHaveLength(1);
    // Only the "contracts" row (first row, sea_claims) carries this —
    // TutorialCoach's spotlight anchors on a single element, not a class of
    // elements; a second occurrence would make the spotlight target
    // ambiguous.
    expect(container.querySelectorAll('[data-tutorial="locate-btn"]')).toHaveLength(1);
  });
});

// ── Representative filter chips ─────────────────────────────────────────
//
// 9 layers spanning 4 different subgroups (sea_claims, sea_life,
// sea_sensors, land_hazards), each driven by a different per-layer const
// def (RISK_FILTERS, IUCN_FILTER_DEFS, CHESS_PHYLUM_DEFS/CHESS_HABITAT_DEFS,
// ALARM_DEFS, WOD_DECADES, SEEP_TYPES) or an inline literal array (fires).
// ⛔ `tailings` was dropped from this list 2026-09-23: its filter chips were
// built on hazard_raw/status, both Global Tailings Portal fields withdrawn
// pending permission — the layer no longer has a filterContent to expand.
// This is the coupling most likely to break in a split, because
// every one of these blocks closes over the parent's `expandedFilter`,
// `toggle`/`toggleExpand`, and one or more filter Sets from the store.
// Labels are the real translated strings from public/locales/en/panels.json
// `layers.<camelCase id>.toggle` — read from source, not invented, so a
// copy change doesn't silently make findRowByLabel fall through undetected.
const FILTER_LAYERS: Array<{ id: string; label: string }> = [
  { id: "contracts", label: "Mining Concessions" },
  { id: "biodiversity-hotspots", label: "OBIS Species (Deep)" },
  { id: "chess", label: "Chemosynthetic Sites" },
  { id: "argo", label: "Argo Floats" },
  { id: "wod-oxygen", label: "Historical Oxygen Profiles (WOD)" },
  { id: "methane-seeps", label: "Methane Seeps (SEAFLEA)" },
  { id: "ais-live", label: "Live Vessels (AIS)" },
  { id: "submarine-cables", label: "Submarine Cables" },
  { id: "fires", label: "Active Fires (FIRMS)" },
];

function findRowByLabel(container: HTMLElement, label: string): HTMLElement {
  const span = [...container.querySelectorAll("span")].find((el) => el.textContent === label);
  if (!span) throw new Error(`Row for "${label}" not found — label text may have changed`);
  const row = span.closest(".relative");
  if (!row) throw new Error(`Row container for "${label}" not found`);
  return row as HTMLElement;
}

describe("Map3DControls representative filters", () => {
  for (const { id, label } of FILTER_LAYERS) {
    it(`expands and snapshots the ${id} filter chips`, async () => {
      seedExpandedPanelState();
      const { container } = render(<Map3DControls {...baseProps} />);
      const row = findRowByLabel(container, label);
      const expandBtn = row.querySelector("button");
      expect(expandBtn).toBeTruthy();
      await act(async () => {
        expandBtn!.click();
      });
      const filterArea = row.querySelector(".pl-5.pb-1\\.5");
      expect(filterArea).toBeTruthy();
      expect(filterArea!.innerHTML).toMatchSnapshot();
    });
  }
});

describe("Map3DControls whole-panel snapshots", () => {
  it("matches the default store state", () => {
    seedExpandedPanelState();
    const { container } = render(<Map3DControls {...baseProps} />);
    expect(container.innerHTML).toMatchSnapshot();
  });

  it("matches with several layers active and one filter expanded", async () => {
    seedExpandedPanelState();
    useMapStore.setState({
      activeLayers: new Set(["contracts", "argo", "biodiversity-hotspots"]),
    });
    const { container } = render(<Map3DControls {...baseProps} />);
    const row = findRowByLabel(container, "Mining Concessions");
    const expandBtn = row.querySelector("button");
    await act(async () => {
      expandBtn!.click();
    });
    expect(container.innerHTML).toMatchSnapshot();
  });
});

// ── The 10 parent props ─────────────────────────────────────────────────
//
// Several rows (ocean-currents, woa-climatology, ocean-carbon,
// ocean-co2-surface, oxygen-deox) only render their variable/depth
// selectors when the matching meta prop is present — so a snapshot with
// every prop null/undefined and one with every prop populated must differ,
// or the split silently dropped the prop-gated branch.
describe("Map3DControls parent props", () => {
  it("matches with every optional prop null/undefined", () => {
    seedExpandedPanelState();
    const { container } = render(<Map3DControls {...baseProps} />);
    expect(container.innerHTML).toMatchSnapshot();
  });

  it("matches with every optional prop populated (real shapes from Props)", () => {
    seedExpandedPanelState();
    useMapStore.setState({ activeLayers: new Set(["ocean-currents", "woa-climatology", "ocean-carbon", "ocean-co2-surface", "oxygen-deox"]) });
    const { container } = render(
      <Map3DControls
        {...baseProps}
        currentsMeta={{ surface: currentsMetaFull.surface, "1000m": currentsMetaFull.surface }}
        woaMeta={woaMetaFull}
        oxygenMeta={oxygenMetaFull}
        carbonMeta={carbonMetaFull}
        co2Meta={co2MetaFull}
      />,
    );
    expect(container.innerHTML).toMatchSnapshot();
  });
});
